#!/usr/bin/with-contenv bash

# This file is placed in the proper location to be executed at container-startup time.
# These variables are available as container env vars, and not as build args. They are not
# hard coded onto the image, in other words.

sed -i "s,__ICECAST_FQDN__,${ICECAST_FQDN},g" 		/etc/mpd.conf
sed -i "s,__ICECAST_PORT__,${ICECAST_PORT},g" 		/etc/mpd.conf
sed -i "s,__ICECAST_PASSWORD__,${ICECAST_PASSWORD},g" 	/etc/mpd.conf
sed -i "s,__CHANNEL_SUFFIX__,${CHANNEL_SUFFIX},g" 	/etc/mpd.conf
echo -----------------------------------
cat /etc/mpd.conf
echo -----------------------------------
